services:

  spark-master:
    container_name: spark-master
    build:
      context: .
      dockerfile: build/Dockerfile.spark
    image: my_spark_standalone_cluster:latest
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - .:/opt/spark/app-etl
      - ./logs:/opt/spark/logs
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    container_name: spark-worker-a
    build:
      context: .
      dockerfile: build/Dockerfile.spark
    image: my_spark_standalone_cluster:latest
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - .:/opt/spark/app-etl
      - ./logs:/opt/spark/logs

  spark-worker-b:
    container_name: spark-worker-b
    build:
      context: .
      dockerfile: build/Dockerfile.spark
    image: my_spark_standalone_cluster:latest
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - .:/opt/spark/app-etl
      - ./logs:/opt/spark/logs

  spark-worker-c:
    container_name: spark-worker-c
    build:
      context: .
      dockerfile: build/Dockerfile.spark
    image: my_spark_standalone_cluster:latest
    ports:
      - "9093:8080"
      - "7003:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-c
    volumes:
      - .:/opt/spark/app-etl
      - ./logs:/opt/spark/logs

  spark-worker-d:
    container_name: spark-worker-d
    build:
      context: .
      dockerfile: build/Dockerfile.spark
    image: my_spark_standalone_cluster:latest
    ports:
      - "9094:8080"
      - "7004:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-d
    volumes:
      - .:/opt/spark/app-etl
      - ./logs:/opt/spark/logs
